# Generated by Django 3.0.3 on 2020-02-15 19:56

from django.db import migrations, models
import django.db.models.deletion
import inspection_reporter.utils.records_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('inspection_id', models.IntegerField(unique=True)),
                ('inspection_date', models.DateField(validators=[inspection_reporter.utils.records_validators.valid_date])),
                ('score', models.IntegerField(validators=[inspection_reporter.utils.records_validators.valid_score])),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('restaurant_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('street_address', models.TextField(validators=[inspection_reporter.utils.records_validators.valid_address])),
                ('city', models.TextField()),
                ('state', models.CharField(max_length=2, validators=[inspection_reporter.utils.records_validators.valid_state_abbrev])),
                ('postal_code', models.CharField(blank=True, max_length=5, validators=[inspection_reporter.utils.records_validators.valid_zip])),
                ('is_current', models.BooleanField(default=True)),
                ('average_score', models.DecimalField(decimal_places=2, default=-1.0, max_digits=5)),
                ('average_violations', models.DecimalField(decimal_places=2, default=-1.0, max_digits=5)),
                ('total_inspection', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('violation_id', models.IntegerField(unique=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('is_repeat', models.BooleanField(default=False)),
                ('is_corrected_on_site', models.BooleanField(default=False)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='records.Inspection', to_field='inspection_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('name', 'street_address'), name='unique_restaurant'),
        ),
        migrations.AddField(
            model_name='inspectionviolation',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Inspection', to_field='inspection_id'),
        ),
        migrations.AddField(
            model_name='inspectionviolation',
            name='violation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Violation', to_field='violation_id'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='records.Restaurant', to_field='restaurant_id'),
        ),
        migrations.AddConstraint(
            model_name='inspectionviolation',
            constraint=models.UniqueConstraint(fields=('violation_id', 'inspection_id'), name='unique_inspection_violation'),
        ),
    ]
