# Generated by Django 3.0.3 on 2020-02-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200217_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street_address',
            field=models.TextField(),
        ),
    ]
