# Generated by Django 3.0.3 on 2020-02-18 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200217_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='total_inspection',
            new_name='total_inspections',
        ),
    ]
