# Generated by Django 3.0.3 on 2020-02-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200218_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_violations',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
