# Generated by Django 3.0.3 on 2020-02-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20200218_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='average_score',
            new_name='sum_score',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='average_violations',
            new_name='sum_violations',
        ),
    ]
